import type { SessionMeta } from './core.js';
import type { SessionFts, FtsMessageRow, FtsSessionMeta, SyncSessionRequest, SyncReceipt, SearchFilter, FtsMigrationProgress } from './fts.js';
import type { FtsSpoolCleanupFailure, FtsSpoolInventory } from './fts-spool.js';
export declare const FTS_BATCH_BYTES: number;
export declare const FTS_QUEUE_BYTES: number;
export declare const FTS_INFLIGHT_BATCHES = 2;
export declare const FTS_MAX_QUERY_HITS = 500;
export declare const FTS_SOURCE_BODY_BYTES: number;
export interface FtsRequestOptions {
    signal?: AbortSignal;
    timeoutMs?: number; /** Shared absolute deadline for a multi-batch request. */
    deadlineAt?: number;
    parentRequestId?: string;
}
export interface FtsClientOptions {
    startupTimeoutMs?: number;
    migrationTimeoutMs?: number;
    migrationStallTimeoutMs?: number;
    migrationLockTimeoutMs?: number;
    queryTimeoutMs?: number;
    writeTimeoutMs?: number;
    closeTimeoutMs?: number;
    maxPendingRequests?: number;
    /** Reconcile source/checkpoints after a successful reconnection. */
    onRecovered?: () => void;
    /** Cleanup warnings never change a proven transaction outcome. */
    onSpoolDiagnostic?: (warning: FtsSpoolCleanupFailure) => void;
    /** An injectable transport entrypoint for deterministic transport tests. */
    workerUrl?: URL;
    onStartupProgress?: (event: FtsStartupDiagnostic) => void;
    onStartupFailure?: (event: FtsStartupDiagnostic) => void;
    onRequestDiagnostic?: (event: FtsRequestDiagnostic) => void;
}
export type FtsWorkerRole = 'writer' | 'reader';
export interface FtsStartupDiagnostic {
    role: FtsWorkerRole;
    generation: number;
    state: 'booting' | 'booted' | 'opening' | 'migrating' | 'ready' | 'failed';
    startedAt: number;
    updatedAt: number;
    elapsedMs: number;
    progress?: FtsMigrationProgress;
    error?: FtsWorkerError;
}
export interface FtsRequestDiagnostic {
    requestId: number;
    op: string;
    backend: 'fts';
    role: FtsWorkerRole;
    generation: number;
    parentRequestId?: string;
    startedAt: number;
    totalMs: number;
    readyWaitMs: number;
    recoveryWaitMs: number;
    admissionMs: number;
    queueMs?: number;
    sqlMs?: number;
    dispatchMs?: number;
    serializationMs?: number;
    transportMs?: number;
    healthSnapshotMs?: number;
    /** Estimated remainder: IPC/scheduling plus small uninstrumented client costs. */
    transportIsResidual?: boolean;
    responseTransportMs?: number;
    outcome: 'ok' | 'error' | 'cancelled';
    errorCode?: string;
    timeoutPhase?: 'ready' | 'recovery' | 'admission' | 'queue' | 'execution';
}
export interface FtsWorkerError {
    name: string;
    message: string;
    code: string;
    stack?: string;
    sqliteErrorCode?: number;
}
export declare class FtsRpcError extends Error {
    readonly code: string;
    readonly sqliteErrorCode: number | undefined;
    constructor(error: FtsWorkerError);
}
type EngineResult<K extends keyof SessionFts> = SessionFts[K] extends (...args: never[]) => infer R ? Awaited<R> : never;
export declare function createFtsClient(dbPath: string, options?: FtsClientOptions): Promise<FtsClient | null>;
export declare class FtsClient {
    private readonly dbPath;
    private readonly options;
    private worker;
    private reader;
    private readerSpoolDirectory;
    private readyPromise;
    private writerReadyPromise;
    private readerReadyPromise;
    private restartPromise;
    private readerRestartPromise;
    private readonly startupState;
    private readonly generation;
    private readonly roleRestarts;
    private readonly transportFailures;
    private readonly roleLastError;
    private readerRestartTimes;
    private readerRestartSuspended;
    private diagnosticCallbackError;
    private requestTimeouts;
    private queueTimeouts;
    private cancelledRequests;
    private readonly workerTiming;
    private lastReaderTerminationMs;
    private maxReaderTerminationMs;
    private readonly retiredTerminations;
    private readonly liveChannels;
    private spoolDirectory;
    private sequence;
    private readonly pending;
    private closing;
    private closePromise;
    private writeSequence;
    private readonly writes;
    private failures;
    private activeStreams;
    private queueBytes;
    private maxQueueBytes;
    private inFlightBatches;
    private maxInFlightBatches;
    private maxBatchBytes;
    private readonly batchWaiters;
    private readonly producerWaiters;
    private queuedSourceBytes;
    private activeSourceBytes;
    private maxActiveSourceBytes;
    private activeBodyBytes;
    private maxActiveBodyBytes;
    private restarts;
    private automaticRestartTimes;
    private restartSuspended;
    private degraded;
    private lastTransportError;
    private lastTransportErrorAt;
    private lastRecoveryCallbackError;
    private lastWriteError;
    private lastWriteErrorAt;
    private readonly failedFiles;
    private writerTelemetry;
    private readerTelemetry;
    private maxWriterHeapUsed;
    private maxReaderHeapUsed;
    private maxWriterStagedBytes;
    private readonly ownedSpools;
    private readonly cleanupPendingDirectories;
    private readonly spoolWarnings;
    private readonly seenSpoolWarnings;
    private spoolCleanupFailureCount;
    private lastSpoolDiagnosticCallbackError;
    private spoolInventory;
    private spoolInspection;
    private lastHealth;
    private available;
    constructor(dbPath: string, options?: FtsClientOptions);
    get ok(): boolean;
    ready(): Promise<boolean>;
    private start;
    private startReader;
    private notifyDiagnostic;
    private bootWorker;
    private release;
    private rejectPending;
    private failWorker;
    private recordSpoolWarning;
    private cleanSpool;
    inspectSpools(): Promise<FtsSpoolInventory>;
    restart(reason?: string): Promise<void>;
    private restartReader;
    private withinDeadline;
    private call;
    private write;
    private stream;
    syncSession(request: SyncSessionRequest, options?: FtsRequestOptions): Promise<SyncReceipt>;
    syncMessages(file: string, rows: FtsMessageRow[], append: boolean, options?: FtsRequestOptions): Promise<void>;
    upsertSession(meta: FtsSessionMeta): Promise<void>;
    removeSession(file: string): Promise<void>;
    markPruned(count: number): Promise<void>;
    optimize(): Promise<void>;
    vacuum(): Promise<void>;
    maybeMaintenance(): Promise<void>;
    getCheckpoint(file: string): Promise<EngineResult<'getCheckpoint'>>;
    needsSync(meta: SessionMeta): Promise<boolean>;
    listSessionFiles(): Promise<string[]>;
    sessionCount(): Promise<number>;
    lastPruneAt(): Promise<number>;
    lastPruneCount(): Promise<number>;
    search(query: string, workspace: string, limit: number, filter?: SearchFilter, options?: FtsRequestOptions): Promise<EngineResult<'search'>>;
    searchPage(query: string, workspace: string, limit: number, filter?: SearchFilter, options?: FtsRequestOptions): Promise<EngineResult<'searchPage'>>;
    around(sessionId: string, anchor: number | string, window?: number, options?: FtsRequestOptions): Promise<EngineResult<'around'>>;
    resolveLegacyAnchor(sessionId: string, rowid: number): Promise<EngineResult<'resolveLegacyAnchor'>>;
    diagnostics(): {
        degraded: boolean;
        workerReady: boolean;
        readerReady: boolean;
        restarts: number;
        restartSuspended: boolean;
        writerRestartSuspended: boolean;
        writerRestarts: number;
        readerRestarts: number;
        writerGeneration: number;
        readerGeneration: number;
        writerTransport: "process";
        writerPid: number | undefined;
        readerTransport: "process";
        readerPid: number | undefined;
        liveProcessPids: (number | undefined)[];
        lastReaderTerminationMs: number;
        maxReaderTerminationMs: number;
        writerTransportFailures: number;
        readerTransportFailures: number;
        writerLastTransportError: string;
        readerLastTransportError: string;
        writerPendingRequests: number;
        readerPendingRequests: number;
        readerRestartSuspended: boolean;
        startup: {
            writer?: FtsStartupDiagnostic | undefined;
            reader?: FtsStartupDiagnostic | undefined;
        };
        requestTimeouts: number;
        queueTimeouts: number;
        cancelledRequests: number;
        lastDiagnosticCallbackError: string;
        pendingRequests: number;
        pendingWrites: number;
        activeStreams: number;
        activeSourceBytes: number;
        maxActiveSourceBytes: number;
        activeBodyBytes: number;
        maxActiveBodyBytes: number;
        writerMemory: NodeJS.MemoryUsage | undefined;
        readerMemory: NodeJS.MemoryUsage | undefined;
        maxWriterHeapUsed: number;
        maxReaderHeapUsed: number;
        writerStagedBytes: number;
        maxWriterStagedBytes: number;
        queueBytes: number;
        transportQueueBytes: number;
        queuedSourceBytes: number;
        queuedProducers: number;
        maxQueueBytes: number;
        inFlightBatches: number;
        maxInFlightBatches: number;
        maxBatchBytes: number;
        lastTransportError: string;
        lastTransportErrorAt: number;
        lastRecoveryCallbackError: string;
        lastWriteError: string;
        lastWriteErrorAt: number;
        failedSessions: number;
        spoolCleanupFailures: FtsSpoolCleanupFailure[];
        spoolCleanupFailureCount: number;
        spoolCleanupPendingDirectories: string[];
        spoolCleanupPendingStages: number;
        lastSpoolCleanupError: string;
        lastSpoolDiagnosticCallbackError: string;
        spoolInventory: FtsSpoolInventory | undefined;
        orphanSpoolCount: number;
        unknownSpoolOwnerCount: number;
        acceptingWrites: boolean;
        hostMemory: NodeJS.MemoryUsage;
    };
    health(): Promise<EngineResult<'health'> & ReturnType<FtsClient['diagnostics']> & Record<string, unknown>>;
    flush(): Promise<void>;
    close(): Promise<void>;
}
export {};
