#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin.
# Build: compile src/ → lib/ with the dsh checkout's tsc.
# Requires DSH_CHECKOUT pointing at a dsh source checkout (auto-probe below).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# 未显式指定 DSH_CHECKOUT 时，优先使用本插件 pnpm 锁定的编译器和依赖。
# 这样不会把一个不完整或旧的宿主 checkout 当成构建输入，更不会改写其链接。
CHECKOUT="${DSH_CHECKOUT:-}"
# 完整性 = 后续 link_pkg 真正要用的路径都存在。宿主 checkout 常被裁剪成 stub
# （packages/ 下只剩软链），此时软链指向别处、链接后会得到混版依赖——必须
# 判为不完整，退回 pnpm 锁定的依赖。
checkout_is_complete() {
  [ -d "$1/packages" ] \
    && [ -e "$1/vendor/cordis" ] \
    && [ -e "$1/vendor/cosmokit" ] \
    && [ -e "$1/vendor/schemastery" ] \
    && [ -e "$1/packages/core/tools/package.json" ] \
    && [ -e "$1/packages/llm/llm/package.json" ] \
    && [ -e "$1/packages/core/system-prompt/package.json" ] \
    && { [ -x "$1/node_modules/.bin/tsc" ] || [ -f "$1/node_modules/.bin/tsc.cmd" ]; }
}
if [ -n "$CHECKOUT" ] && ! checkout_is_complete "$CHECKOUT"; then
  if [ -f "node_modules/typescript/bin/tsc" ]; then
    echo "build: DSH_CHECKOUT is incomplete; using local node_modules typescript + locked deps"
    node node_modules/typescript/bin/tsc -p tsconfig.json
    exit $?
  fi
  echo "build: DSH_CHECKOUT is incomplete: $CHECKOUT" >&2
  exit 1
fi
if [ -z "$CHECKOUT" ] && [ -f "node_modules/typescript/bin/tsc" ]; then
  echo "build: DSH_CHECKOUT not set; using local node_modules typescript + locked deps"
  node node_modules/typescript/bin/tsc -p tsconfig.json
  exit $?
fi
if [ -z "$CHECKOUT" ]; then
  for candidate in "$HOME/dsh-harness" "$HOME/dsh" "$HOME/.dsh/dsh-harness"; do
    if checkout_is_complete "$candidate"; then
      CHECKOUT="$candidate"
      break
    fi
  done
fi
if [ -z "$CHECKOUT" ] || [ ! -d "$CHECKOUT/packages" ]; then
  if [ -f "node_modules/typescript/bin/tsc" ]; then
    echo "build: DSH_CHECKOUT not found; using local node_modules typescript + linked deps"
    node node_modules/typescript/bin/tsc -p tsconfig.json
    exit $?
  fi
  echo "build: cannot locate the dsh checkout (set DSH_CHECKOUT) and no local typescript" >&2
  exit 1
fi

TSC="$CHECKOUT/node_modules/.bin/tsc"
if [ ! -x "$TSC" ] && [ ! -f "$TSC.cmd" ]; then
  echo "build: tsc not found at $TSC" >&2
  exit 1
fi

link_pkg() {
  local target="$CHECKOUT/$2"
  if [ ! -e "$target" ]; then
    echo "build: dependency target missing: $target" >&2
    exit 1
  fi
  node -e "
    const fs = require('fs');
    const path = require('path');
    const link = path.resolve(process.argv[1]);
    const target = path.resolve(process.argv[2]);
    fs.rmSync(link, { recursive: true, force: true });
    fs.mkdirSync(path.dirname(link), { recursive: true });
    fs.symlinkSync(target, link, process.platform === 'win32' ? 'junction' : 'dir');
  " "node_modules/$1" "$target"
}

echo "=== Linking build dependencies (checkout: $CHECKOUT) ==="
mkdir -p node_modules/@deepseek-ai
node -e "const fs=require('fs');fs.rmSync('node_modules/@standard-schema',{recursive:true,force:true})"
link_pkg cordis vendor/cordis
link_pkg cosmokit vendor/cosmokit
link_pkg schemastery vendor/schemastery
link_pkg @deepseek-ai/dsh-tools packages/core/tools
link_pkg @deepseek-ai/dsh-llm packages/llm/llm
link_pkg @deepseek-ai/dsh-system-prompt packages/core/system-prompt
# @types/node（编译类型；checkout 自带）
link_pkg @types/node node_modules/@types/node

STD_SCHEMA=$(find "$CHECKOUT/node_modules/.pnpm" -maxdepth 1 -type d -iname '@standard-schema+spec@*' 2>/dev/null | head -1)
if [ -n "$STD_SCHEMA" ]; then
  node -e "
    const fs = require('fs');
    const path = require('path');
    fs.rmSync('node_modules/@standard-schema', { recursive: true, force: true });
    fs.mkdirSync('node_modules/@standard-schema', { recursive: true });
    fs.symlinkSync(path.resolve(process.argv[1]), path.resolve('node_modules/@standard-schema/spec'), process.platform === 'win32' ? 'junction' : 'dir');
  " "$STD_SCHEMA/node_modules/@standard-schema/spec"
fi

echo "=== Compiling src → lib ==="
"$TSC" -p tsconfig.json
echo "=== Build complete ==="
